[package]
name = "loading"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_mes = { path = "../bevy_mes" }
common = { path = "../common" }
dat_repo = { path = "../dat_repo" }