[package]
name = "main_menu"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_art = { path = "../bevy_art" }
bevy_image_font = { path = "../bevy_image_font" }
bevy_mes = { path = "../bevy_mes" }
common = { path = "../common" }
dat_repo = { path = "../dat_repo" }